[Unit]
After=cloud-final.service cloudplay-startup.service plymouth-quit.service
Wants=cloud-final.service cloudplay-startup.service plymouth-quit.service
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
RestartSec=10
StandardOutput=journal
StandardError=journal
