[Unit]
Requires=cloudplay-updater.service cloudplay-maintenance-broker.service
After=cloudplay-updater.service cloudplay-update-bootstrap.service cloudplay-maintenance-broker.service
ConditionPathExists=!/run/cloudplay-update-recovery
ConditionPathExists=!/run/cloudplay-maintenance/active
